### ISSUE TITLE
ENH: Evaluation Progress Tracking

### ISSUE THREAD

**Issue by czaloom** [Striveworks/valor#501]
### Feature Type

- [X] Adding new functionality to valor

- [ ] Changing existing functionality in valor

- [ ] Removing existing functionality in valor

### Problem Description

There is no way to track the progress of an evaluation. This causes issues as the arbitrary setting of timeout in `wait_for_completion` is session dependent (e.g. 30 minute timeout for a 30 s job is not great, and the inverse isnt either.)

### Feature Description

Add a way of tracking the stage of evaluation.

We might be able to estimate time-to-completion based on data type and number of elements too. 

For AP this could be `filtering -> iou computation -> pairing -> ranking -> metric calculation` which could be translated into rough progress percentage.

**Comment by czaloom** [comment]
This has been addressed by #546
