### ISSUE TITLE
ENH: Remove `meta` attribute from `schemas.EvaluationRequest`.

### ISSUE THREAD

**Issue by czaloom** [Striveworks/valor#607]
### Feature Type

- [ ] Adding new functionality to valor

- [ ] Changing existing functionality in valor

- [X] Removing existing functionality in valor

### Problem Description

The `meta` attribute in `schemas.EvaluationRequest` is unused as this is a response-only attribute. User-defined evaluation metadata is not stored so this will only cause confusion for the user.

### Feature Description

Remove the `meta` attribute from `schemas.EvaluationRequest`

### Additional Context

`meta` is still an attribute of `schemas.EvaluationResponse`
